"""Lightweight foundation systems for Shinobi RPG MVP."""

from .core import (
    Affinity,
    Backstory,
    Move,
    MoveCategory,
    NinjaWorld,
    PlayerProfile,
    Quest,
    Region,
    ReputationTier,
    Trophy,
    TrophyCategory,
    VillainProfile,
    VillainStance,
    Weapon,
    WeaponType,
    assign_affinity_from_choices,
    build_mvp_world,
    resolve_affinity_minigame,
)

__all__ = [
    "Affinity",
    "Backstory",
    "Move",
    "MoveCategory",
    "NinjaWorld",
    "PlayerProfile",
    "Quest",
    "Region",
    "ReputationTier",
    "Trophy",
    "TrophyCategory",
    "VillainProfile",
    "VillainStance",
    "Weapon",
    "WeaponType",
    "assign_affinity_from_choices",
    "build_mvp_world",
    "resolve_affinity_minigame",
]
