"""Lightweight foundation systems for Shinobi RPG MVP."""

__version__ = "0.1.0"

from .core import (
    Affinity,
    ArcDefinition,
    Backstory,
    JutsuType,
    Move,
    MoveCategory,
    MoveSkin,
    NinjaWorld,
    PlayerProfile,
    Quest,
    QuestStatus,
    Region,
    ReputationTier,
    StatusEffectType,
    Trophy,
    TrophyCategory,
    TrophyTier,
    VillainProfile,
    VillainStance,
    Weapon,
    WeaponType,
    assign_affinity_from_choices,
    build_mvp_world,
    load_world_snapshot,
    resolve_affinity_minigame,
    save_world_snapshot,
)
from .framework import framework_overview_json, get_framework_overview

__all__ = [
    "__version__",
    "Affinity",
    "ArcDefinition",
    "Backstory",
    "JutsuType",
    "Move",
    "MoveCategory",
    "MoveSkin",
    "NinjaWorld",
    "PlayerProfile",
    "Quest",
    "QuestStatus",
    "Region",
    "ReputationTier",
    "StatusEffectType",
    "Trophy",
    "TrophyCategory",
    "TrophyTier",
    "VillainProfile",
    "VillainStance",
    "Weapon",
    "WeaponType",
    "assign_affinity_from_choices",
    "build_mvp_world",
    "load_world_snapshot",
    "resolve_affinity_minigame",
    "save_world_snapshot",
    "get_framework_overview",
    "framework_overview_json",
]
