from __future__ import annotations

__all__ = [
    # Enums
    "Affinity",
    "MoveCategory",
    "TechniqueType",
    "WeaponType",
    "StatusEffectType",
    "VillainStance",
    "TrophyCategory",
    "TrophyTier",
    "ReputationTier",
    "QuestStatus",
    # Dataclass models
    "Move",
    "Weapon",
    "MoveSkin",
    "Skin",
    "Backstory",
    "ArcDefinition",
    "RivalProfile",
    "BossEchoForm",
    "VillainProfile",
    "Trophy",
    "Quest",
    "PointOfInterest",
    "CityShop",
    "CityNPC",
    "Region",
    "PlayerStats",
    "PlayerProfile",
    "NinjaWorld",
    # Public constants
    "AFFINITY_RESONANCE_PAIRS",
    "ALLY_COMBAT_ABILITIES",
    "BASE_XP_PER_LEVEL",
    "BOSS_ECHO_POWER_SCALE_BOOST",
    "CHAKRA_COST",
    "CHAKRA_MAX",
    "CHAKRA_REGEN_ESCAPE",
    "CHAKRA_START",
    "DEFAULT_ALLY_MIN_COUNT",
    "HEROIC_THRESHOLD_MIN",
    "KARMIC_INHERITANCE_REP_BONUS",
    "KILL_REP_LOSS",
    "MOVE_PROFICIENCY_DEFAULT",
    "MOVE_PROFICIENCY_MAX",
    "MOVE_PROFICIENCY_LOW_THRESHOLD",
    "MOVE_PROFICIENCY_SCALE_FLOOR",
    "MOVE_TRAIN_CREDIT_COST",
    "NONLETHAL_CHARM_MASTER_THRESHOLD",
    "NONLETHAL_CHARM_REP_GAIN",
    "NONLETHAL_EVASION_MASTER_THRESHOLD",
    "NONLETHAL_EVASION_REP_GAIN",
    "NONLETHAL_FLOW_CHAIN_THRESHOLD",
    "NONLETHAL_STEALTH_MASTER_THRESHOLD",
    "NONLETHAL_STEALTH_REP_GAIN",
    "PATROL_STATE_ALERTED",
    "PATROL_STATE_COMBAT_LOCKED",
    "PATROL_STATE_UNDETECTED",
    "REPUTATION_DECAY_AMOUNT",
    "REPUTATION_DECAY_INACTIVITY_TICKS",
    "ROGUE_THRESHOLD_MIN",
    "SCOUTING_INTEL_CATEGORIES",
    "STATUS_EFFECT_BANDS",
    "TROPHY_BATTLE_HARDENED",
    "TROPHY_GHOST_STEP",
    "WEAPON_DURABILITY_LOW_THRESHOLD",
    "WEAPON_DURABILITY_MAX",
    "WEAPON_DURABILITY_SCALE_FLOOR",
    "WEAPON_DURABILITY_START",
    "WEAPON_REPAIR_CREDIT_COST_BASE",
    # Public functions
    "assign_affinity_from_choices",
    "build_mvp_world",
    "enemy_exclusive_move_for",
    "get_learnable_enemy_moves",
    "load_world_snapshot",
    "resolve_affinity_minigame",
    "save_world_snapshot",
]

from ._types import *
from ._constants import *
from ._models import *
from ._world import *
from ._seed import *
